name: Periodic sync & publish

# Controls when the workflow will run
on:
  schedule:
    - cron: "00 17 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Send HTTP POST request to https://backend.autoaws.cz/api/github
        # You may pin to the exact commit or the version.
        # uses: fjogeleit/http-request-action@f986377e36f4e3d86c0c42523e02b844785182e9
        uses: fjogeleit/http-request-action@v1.9.1
        with:
          url: https://backend.autoaws.cz/api/github
          method: POST
          data: ${{ secrets.GITHUBTRIGGERTOKEN }}
          preventFailureOnNoResponse: true
          timeout: 30000
